<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config["database_schema"] = array(
    // このファイルは自動で生成されるファイルである。
    // データベースのスキーマを更新した場合は、こちらのファイルを生成し直すこと。
    // データベースのスキーマとこのファイルに差分がある状態で本番環境へ移行すると不具合の原因になるので注意すること。

    'schooltv_main' => array(

        'action_history' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'object' => array('type' => 'string', 'strict_type' => "char(32)", 'null' => 0),
            'action' => array('type' => 'string', 'strict_type' => "char(32)", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 1),
            'extra_data' => array('type' => 'string', 'strict_type' => "longtext", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'admin' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'login_id' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 1),
            'status' => array('type' => 'string', 'strict_type' => "enum('active','suspended')", 'null' => 0),
            'password' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 0),
            'role_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'admin_login_token' => array(
            'admin_id' => array('type' => 'string', 'strict_type' => "bigint(20) unsigned", 'null' => 0),
            'token' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 0),
            'user_agent' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'remote_ip' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'avatar' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'battle_room' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'group_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'target_group_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'stage_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'time_limit' => array('type' => 'string', 'strict_type' => "int(11) unsigned", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('open','close')", 'null' => 0),
            'extra_data' => array('type' => 'string', 'strict_type' => "longtext", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'cache_textbook_count' => array(
            'textbook_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'count' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
        ),

        'campaign' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(110)", 'null' => 0),
            'code' => array('type' => 'string', 'strict_type' => "varchar(110)", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('inactive','active','suspended')", 'null' => 0),
            'started_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'ended_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'ci_sessions' => array(
            'id' => array('type' => 'string', 'strict_type' => "varchar(40)", 'null' => 0),
            'ip_address' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'timestamp' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'data' => array('type' => 'string', 'strict_type' => "blob", 'null' => 0),
        ),

        'contact' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'type' => array('type' => 'string', 'strict_type' => "tinyint(2) unsigned", 'null' => 0),
            'question' => array('type' => 'string', 'strict_type' => "longtext", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'credit_card' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'card_number' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'password' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 0),
            'card_seq' => array('type' => 'string', 'strict_type' => "tinyint(3)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'group' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'primary_type' => array('type' => 'string', 'strict_type' => "enum('family','friend')", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 0),
            'highest_score' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 1),
            'avatar_id' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'group_invite' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'group_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'email' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 0),
            'token' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'expired_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'group_playing' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'group_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('quest','event','battle')", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('open','progress','failed','close','success')", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'learning_history' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "int(1)", 'null' => 0),
            'video_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'question_answer_data' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'second' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'master_area' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'pref_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'area_code' => array('type' => 'string', 'strict_type' => "varchar(10)", 'null' => 0),
        ),

        'master_area_pref' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'group_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
        ),

        'master_area_pref_group' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(12)", 'null' => 0),
        ),

        'master_grade' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
        ),

        'master_postalcode' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'postalcode' => array('type' => 'string', 'strict_type' => "char(7)", 'null' => 0),
        ),

        'master_school' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'area_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'postalcode_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('elementary','juniorhigh','secondary')", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'address' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'kind' => array('type' => 'string', 'strict_type' => "enum('national','public','private','startcompany')", 'null' => 0),
            'short_name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'students' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'kcode' => array('type' => 'string', 'strict_type' => "varchar(15)", 'null' => 0),
        ),

        'master_subject' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'grade_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'short_name' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'rubi' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'color' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'display_flag' => array('type' => 'string', 'strict_type' => "int(1)", 'null' => 0),
        ),

        'master_textbook_inuse' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'school_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'year_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'subject_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'textbook_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
        ),

        'master_year' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(32)", 'null' => 0),
        ),

        'message' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'room_id' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'message' => array('type' => 'string', 'strict_type' => "text", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'news' => array(
            'id' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'title' => array('type' => 'string', 'strict_type' => "text", 'null' => 0),
            'content' => array('type' => 'string', 'strict_type' => "text", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('private','public')", 'null' => 0),
            'started_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'ended_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'notification' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "tinyint(1)", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "varchar(32)", 'null' => 0),
            'extra_data' => array('type' => 'string', 'strict_type' => "text", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'page' => array(
            'id' => array('type' => 'string', 'strict_type' => "int(11) unsigned", 'null' => 0),
            'key' => array('type' => 'string', 'strict_type' => "varchar(155)", 'null' => 0),
            'title' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'content' => array('type' => 'string', 'strict_type' => "longtext", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('private','public')", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 1),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'permission' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'identifier' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 0),
            'description' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'point' => array(
            'id' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'case' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'title_modal' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'base_point' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'condition' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 1),
            'type' => array('type' => 'string', 'strict_type' => "enum('single','continuous','limited')", 'null' => 0),
            'campaign' => array('type' => 'string', 'strict_type' => "tinyint(4)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'point_exchange' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'ip_address' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'point' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'mile' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'publish_id' => array('type' => 'string', 'strict_type' => "varchar(32)", 'null' => 1),
            'status' => array('type' => 'string', 'strict_type' => "enum('wait','done','reject','error','expired')", 'null' => 0),
            'extra_data' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'price' => array(
            'type' => array('type' => 'string', 'strict_type' => "enum('coin','mile')", 'null' => 0),
            'price' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'number' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'publisher' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'short_name' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'purchase' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'order_id' => array('type' => 'string', 'strict_type' => "varchar(60)", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'coin' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'amount' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('pending','success')", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('contract','coin')", 'null' => 0),
            'data' => array('type' => 'string', 'strict_type' => "longblob", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'ranking' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('score','deck')", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 0),
            'score' => array('type' => 'float', 'strict_type' => "float", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'role' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'identifier' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'order' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'role_permission' => array(
            'role_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'permission_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'room' => array(
            'id' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 1),
            'type' => array('type' => 'string', 'strict_type' => "enum('private','family','friend')", 'null' => 0),
            'group_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'room_user' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'room_id' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'last_time' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'sitemap' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('sitemap','video')", 'null' => 1),
            'filename' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'data' => array('type' => 'string', 'strict_type' => "longblob", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'textbook' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'year_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'publisher_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'subject_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'textbook_content' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'textbook_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'deck_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'chapter_name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 1),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'order' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'description' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'video_id' => array('type' => 'string', 'strict_type' => "varchar(32)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'timeline' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('trophy','timeline')", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'play_type' => array('type' => 'string', 'strict_type' => "enum('video','individual_play','team_play')", 'null' => 1),
            'play_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'extra_data' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'timeline_comment' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'timeline_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'content' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'timeline_good' => array(
            'timeline_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'trophy' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'description' => array('type' => 'string', 'strict_type' => "text", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('tutorial','progress','special')", 'null' => 0),
            'category' => array('type' => 'string', 'strict_type' => "varchar(32)", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 1),
            'image_key' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'login_id' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 0),
            'primary_type' => array('type' => 'string', 'strict_type' => "enum('student','parent')", 'null' => 0),
            'email' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 0),
            'nickname' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 1),
            'current_coin' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'highest_score' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 1),
            'current_school' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'current_grade' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'status' => array('type' => 'string', 'strict_type' => "enum('active','suspended','unauth')", 'null' => 1),
            'password' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 0),
            'email_verified' => array('type' => 'string', 'strict_type' => "int(1)", 'null' => 0),
            'invited_from_id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 1),
            'registered_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_buying' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('deck','expired')", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'coin' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_contract' => array(
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'expired_time' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'next_purchase_time' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'status' => array('type' => 'string', 'strict_type' => "enum('free','under_contract','canceling','pending','not_contract')", 'null' => 0),
            'purchase_id' => array('type' => 'string', 'strict_type' => "bigint(20) unsigned", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_contract_history' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'parent_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'purchase_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'type' => array('type' => 'string', 'strict_type' => "enum('first_register','auto_purchase_26th','try_auto_purchase_26th','pending_11th','manually_purchase_pending','cancel','turn_off_25th','turn_off_cancel')", 'null' => 0),
            'content' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'status' => array('type' => 'string', 'strict_type' => "enum('fail','success')", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_email_verify' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'token' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'expired_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_extra_type' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'extra_type' => array('type' => 'string', 'strict_type' => "varchar(16)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_friend' => array(
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('active','request','inactive')", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_friend_number' => array(
            'number' => array('type' => 'string', 'strict_type' => "varchar(4)", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'register_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
        ),

        'user_grade_history' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'grade_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'registered_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_group' => array(
            'group_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'role' => array('type' => 'string', 'strict_type' => "enum('owner','admin','member')", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_group_playing' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'group_playing_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'second' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'score' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'question_answer_data' => array('type' => 'string', 'strict_type' => "longtext", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('progress','fail','success')", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_invitation_code' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'code' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_login_token' => array(
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(20) unsigned", 'null' => 0),
            'token' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 0),
            'user_agent' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'remote_ip' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_memorization' => array(
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'memorization_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('remember','forget','consider')", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_netmile' => array(
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'netmile_user_id' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 0),
            'enc_user_id' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_news' => array(
            'id' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'news_id' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'is_read' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_oauth' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(20) unsigned", 'null' => 0),
            'oauth_id' => array('type' => 'string', 'strict_type' => "bigint(20) unsigned", 'null' => 0),
            'access_token' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 1),
            'type' => array('type' => 'string', 'strict_type' => "enum('facebook','twitter')", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_password_verify' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'token' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'expired_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_playing_stage' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'stage_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'second' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'score' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('battle','training','trial','memorize')", 'null' => 0),
            'question_answer_data' => array('type' => 'string', 'strict_type' => "longtext", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_power' => array(
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'max_power' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'current_power' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_profile' => array(
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'avatar_id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 0),
            'birthday' => array('type' => 'date', 'strict_type' => "date", 'null' => 1),
            'gender' => array('type' => 'string', 'strict_type' => "enum('male','female')", 'null' => 1),
            'postalcode' => array('type' => 'string', 'strict_type' => "char(7)", 'null' => 1),
            'address' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 1),
            'phone' => array('type' => 'string', 'strict_type' => "varchar(32)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_promotion_code' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "varchar(32)", 'null' => 0),
            'code' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_question_answer' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'deck_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'question_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'second' => array('type' => 'float', 'strict_type' => "float", 'null' => 1),
            'correct' => array('type' => 'string', 'strict_type' => "tinyint(1)", 'null' => 0),
            'answer' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_rabipoint' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'rabipoint' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'point_remain' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'is_modal_shown' => array('type' => 'string', 'strict_type' => "tinyint(1)", 'null' => 0),
            'point_id' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 1),
            'type' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'target_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'extra_data' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'user_school_history' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'school_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'registered_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_textbook_inuse' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'grade_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'textbook_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_trophy' => array(
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'trophy_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'user_video_count_second' => array(
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(20) unsigned", 'null' => 0),
            'second' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
        ),
    ),

    'schooltv_mail' => array(

        'mail_queue' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'status' => array('type' => 'string', 'strict_type' => "enum('waiting','sending','succeed','failed')", 'null' => 0),
            'sent_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'from_name' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 0),
            'from_address' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 0),
            'to' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 0),
            'bcc' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 1),
            'header' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 1),
            'priority' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 1),
            'subject' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'content_type' => array('type' => 'string', 'strict_type' => "enum('plain','html')", 'null' => 0),
            'content' => array('type' => 'string', 'strict_type' => "text", 'null' => 0),
            'pushed_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'requesting_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'sent_evidence' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 1),
            'type_user' => array('type' => 'string', 'strict_type' => "tinyint(1)", 'null' => 1),
            'extra_data' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'type_id' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'mail_template' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'content_type' => array('type' => 'string', 'strict_type' => "enum('plain','html')", 'null' => 0),
            'from_address' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 0),
            'from_name' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 1),
            'subject' => array('type' => 'string', 'strict_type' => "text", 'null' => 0),
            'content' => array('type' => 'string', 'strict_type' => "text", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 1),
        ),
    ),

    'schooltv_content' => array(

        'deck' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'package_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'category_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'description' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'coin' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'image_key' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 1),
            'order' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'key' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'deck_category' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'title' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'package_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'key' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'deck_image' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'deck_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'image_key' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
        ),

        'deck_package' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'title' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'subject_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'grade_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'deck_video_inuse' => array(
            'deck_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'video_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
        ),

        'memorization' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(20) unsigned", 'null' => 0),
            'stage_id' => array('type' => 'string', 'strict_type' => "bigint(20) unsigned", 'null' => 0),
            'key' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'answer' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'question' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'sound_key' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'order' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'quest' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'title' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'description' => array('type' => 'string', 'strict_type' => "text", 'null' => 0),
            'stage_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('average','win','accuracy','combo')", 'null' => 0),
            'drill_type' => array('type' => 'string', 'strict_type' => "enum('battle','training')", 'null' => 0),
            'clear_condition_1' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 1),
            'clear_condition_2' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 1),
            'key' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'order' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'question' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'question_key' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'type' => array('type' => 'string', 'strict_type' => "varchar(16)", 'null' => 0),
            'deck_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'data' => array('type' => 'string', 'strict_type' => "longtext", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'stage' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 0),
            'deck_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'order' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 1),
            'key' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'stage_question_inuse' => array(
            'stage_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'question_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
        ),

        'video' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'type' => array('type' => 'string', 'strict_type' => "enum('textbook','active_learning')", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "tinytext", 'null' => 1),
            'description' => array('type' => 'string', 'strict_type' => "text", 'null' => 1),
            'brightcove_id' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 0),
            'brightcove_thumbnail_url' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 1),
            'image_key' => array('type' => 'string', 'strict_type' => "varchar(192)", 'null' => 1),
            'duration' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'video_progress' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 0),
            'video_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'cookie_id' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 1),
            'session_id' => array('type' => 'string', 'strict_type' => "varchar(16)", 'null' => 1),
            'second' => array('type' => 'float', 'strict_type' => "float", 'null' => 0),
            'duration' => array('type' => 'float', 'strict_type' => "float", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "timestamp", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'done_flag' => array('type' => 'string', 'strict_type' => "int(1)", 'null' => 0),
        ),

        'video_question_timeline' => array(
            'video_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'question_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'second' => array('type' => 'float', 'strict_type' => "float unsigned", 'null' => 0),
        ),

        'video_rabi_count' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'video_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'button_id' => array('type' => 'string', 'strict_type' => "tinyint(1)", 'null' => 0),
            'user_id' => array('type' => 'string', 'strict_type' => "bigint(20)", 'null' => 0),
            'second' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'video_view_count' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'video_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'count' => array('type' => 'string', 'strict_type' => "int(11)", 'null' => 0),
            'date' => array('type' => 'date', 'strict_type' => "date", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),
    ),

    'schooltv_image' => array(

        'file' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'key' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 0),
            'data' => array('type' => 'string', 'strict_type' => "longblob", 'null' => 0),
            'size' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'content_type' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 0),
            'holder_type' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'source_url' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 1),
            'secure' => array('type' => 'string', 'strict_type' => "tinyint(1)", 'null' => 0),
            'holder_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),

        'image' => array(
            'id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 0),
            'parent_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'type' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'key' => array('type' => 'string', 'strict_type' => "varchar(64)", 'null' => 0),
            'name' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 0),
            'content_type' => array('type' => 'string', 'strict_type' => "varchar(128)", 'null' => 0),
            'data' => array('type' => 'string', 'strict_type' => "longblob", 'null' => 0),
            'size' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'width' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'height' => array('type' => 'string', 'strict_type' => "int(10) unsigned", 'null' => 0),
            'source_url' => array('type' => 'string', 'strict_type' => "varchar(255)", 'null' => 1),
            'holder_type' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
            'holder_id' => array('type' => 'string', 'strict_type' => "bigint(19) unsigned", 'null' => 1),
            'secure' => array('type' => 'string', 'strict_type' => "tinyint(1)", 'null' => 0),
            'created_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'created_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'updated_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 0),
            'updated_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 0),
            'deleted_at' => array('type' => 'datetime', 'strict_type' => "datetime", 'null' => 1),
            'deleted_by' => array('type' => 'string', 'strict_type' => "varchar(45)", 'null' => 1),
        ),
    ),
);

